#!/bin/bash
########################################################################################
# Creates a new instance of the Vilfredo application in a completely independent folder.
# This requires the /home/vilfredo-setup folder to be existing
# (in order to copy files into the new instance).
# Files will be downloaded from the specified GIT repository branch.
# Developed by Massimiliano Alessandri <massimiliano.alessandri@gmail.com>
########################################################################################
if [ "$4" == "" ]; then
  echo "Usage: $0 [name of instance to be created] [domain] [branch] [mysql database password]"
  echo "A new home folder and user will be created with the name of the instance."
	echo "Note: The instance name must be different from the name of any folder in /etc"
	echo "Developed by Massimiliano Alessandri <massimiliano.alessandri@gmail.com>"
  exit
fi

if [ -d "/etc/$NAME" ]; then
	echo "The /etc/$NAME folder already exists. Cannot create this instance."
	echo "If the instance has to be recreated, first delete the /etc/$NAME folder."
	exit
fi

NAME=$1
FOLDER=/home/$1
USER=$1
DOMAIN=$2
BRANCH=$3
PASSWORD=$4
SETUPFOLDER=/home/vilfredo/vilfredo-setup

########################################
# Create user and download Vilfredo code
########################################
adduser $USER
mkdir -p $FOLDER
cd $FOLDER
git clone -b $BRANCH https://github.com/fairdemocracy/vilfredo-core.git
git clone -b $BRANCH https://github.com/fairdemocracy/vilfredo-client.git
virtualenv vilfredo-ve --python=/usr/bin/pypy
. vilfredo-ve/bin/activate
pip install -U setuptools
pip install itsdangerous==0.23
pip install argparse==1.2.1
pip install alembic==0.7.4
pip install Flask-Script==0.6.7
pip install Flask-Migrate==1.3.0
pip install Pillow==2.8.1
pip install requests==2.7.0
pip install ipython==4.0.0
pip install Flask==0.10
pip install Flask-Mail==0.8.2
pip install Flask-Babel==0.8
pip install Flask-Login==0.2.6
pip install SQLAlchemy==0.8.2
pip install Flask-SQLAlchemy==1.0
pip install Flask-CDN==1.2.1
pip install flask-util-js==0.2.19
pip install MySQL-python==1.2.5
pip install pyparsing==1.5.7
pip install pydot==1.0.2
chown -R $USER vilfredo-client
chown -R $USER vilfredo-core
chown -R $USER:users vilfredo-ve

#################
# Create database
#################
# Note: This assumes password is stored in ".my.cnf" file
mysql -e "CREATE DATABASE $NAME;GRANT ALL PRIVILEGES ON $USER.* TO $NAME@localhost IDENTIFIED BY '$PASSWORD'"
mysql $NAME < $SETUPFOLDER/database.sql

####################
# Configure instance
####################
mkdir -p /etc/$NAME
chown $USER:users /etc/$NAME
chmod 701 /etc/$NAME
cp -a $SETUPFOLDER/settings.cfg /etc/$NAME
replace "www.vilfredo.org" $DOMAIN -- /etc/$NAME/settings.cfg
replace /home/vilfredo $FOLDER -- /etc/$NAME/settings.cfg
replace "vilfredo:" "$USER:" -- /etc/$NAME/settings.cfg
replace "localhost/vilfredo" "localhost/$NAME" -- /etc/$NAME/settings.cfg
replace "/var/log/vilfredo" "/var/log/$NAME" -- /etc/$NAME/settings.cfg
ln -sf /etc/$NAME/settings.cfg $FOLDER/vilfredo-core/VilfredoReloadedCore
mv -a $FOLDER/vilfredo-client/static/js/settings.js /etc/$NAME
replace "https" "http" -- /etc/$NAME/settings.js
echo Do not forget to check /etc/$NAME/settings.js and change the protocol to https if needed
ln -s /etc/$NAME/settings.js $FOLDER/vilfredo-client/static/js
cp -a $SETUPFOLDER/logging_debug.conf /etc/$NAME
replace "var/log/vilfredo" "var/log/$NAME" -- /etc/$NAME/logging_debug.conf
ln -sf /etc/$NAME/logging_debug.conf $FOLDER/vilfredo-core/VilfredoReloadedCore
chown $USER /etc/$NAME/settings.cfg

######################
# Configure web server
######################
mkdir -p "/var/log/$NAME"
chown -R $USER:adm /var/log/$NAME
mkdir -p "/var/log/nginx/$NAME"
cp -a $SETUPFOLDER/instance-nginx /etc/nginx/sites-available/$NAME.conf
replace www.vilfredo.org $DOMAIN -- /etc/nginx/sites-available/$NAME.conf
replace /home/vilfredo $FOLDER -- /etc/nginx/sites-available/$NAME.conf
replace uwsgi_vilfredo uwsgi_$NAME -- /etc/nginx/sites-available/$NAME.conf
replace "/var/log/nginx/vilfredo" "/var/log/nginx/$NAME" -- /etc/nginx/sites-available/$NAME.conf
ln -sf /etc/nginx/sites-available/$NAME.conf /etc/nginx/sites-enabled
cp -a $SETUPFOLDER/vilfredo-uwsgi.ini /etc/uwsgi-pypy/apps-available/$NAME.ini
replace uwsgi_vilfredo uwsgi_$NAME -- /etc/uwsgi-pypy/apps-available/$NAME.ini
replace /home/vilfredo $FOLDER -- /etc/uwsgi-pypy/apps-available/$NAME.ini
replace "uid=vilfredo" "uid=$USER" -- /etc/uwsgi-pypy/apps-available/$NAME.ini
ln -sf /etc/uwsgi-pypy/apps-available/$NAME.ini /etc/uwsgi-pypy/apps-enabled
ln -sf $FOLDER/vilfredo-client/static $FOLDER/vilfredo-core/VilfredoReloadedCore
ln -sf $FOLDER/vilfredo-client/templates $FOLDER/vilfredo-core/VilfredoReloadedCore
chown $USER -R $FOLDER
chmod -R o-r,o-x $FOLDER
service uwsgi-pypy restart
service nginx restart

echo "Instance $NAME installed."
